"""followers

Revision ID: 13253724d1f8
Revises: b45dd7256b41
Create Date: 2019-05-27 19:09:57.776301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13253724d1f8'
down_revision = 'b45dd7256b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
