"""changed name of Product table to 'products'

Revision ID: e46271ad2de8
Revises: 8a0aa6bbc3c9
Create Date: 2019-06-01 12:02:48.336674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46271ad2de8'
down_revision = '8a0aa6bbc3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('thumbnail', sa.String(length=256), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=140), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=256), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    # ### end Alembic commands ###
